version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: eduplatform-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=eduplatform
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped
    networks:
      - eduplatform-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: ghcr.io/ovosimpatico/eduplatform-backend:latest
    container_name: eduplatform-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:admin123@eduplatform-mongodb:27017/eduplatform?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - eduplatform-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    # build:
    #   context: ./frontend
    #   dockerfile: Dockerfile
    image: ghcr.io/ovosimpatico/eduplatform-frontend:latest
    container_name: eduplatform-frontend
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - eduplatform-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  eduplatform-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
